echo calling sequence 1 ...
 ./build/MotionDetector /home/guoqing/Datasets/CDW-2014/dataset/baseline/highway/input 4
echo calling sequence 2 ...
./build/MotionDetector /home/guoqing/Datasets/CDW-2014/dataset/baseline/office/input 4
echo calling sequence 3 ...
./build/MotionDetector /home/guoqing/Datasets/CDW-2014/dataset/baseline/pedestrians/input 4
echo calling sequence 4 ...
./build/MotionDetector /home/guoqing/Datasets/CDW-2014/dataset/baseline/PETS2006/input 4
echo Done.
