echo calling sequence 1 ...
./build/background_subtraction /home/guoqing/Datasets/CDW-2014/dataset/baseline/highway/input 2
echo calling sequence 2 ...
./build/background_subtraction /home/guoqing/Datasets/CDW-2014/dataset/baseline/office/input 2\
echo calling sequence 3 ...
./build/background_subtraction /home/guoqing/Datasets/CDW-2014/dataset/baseline/pedestrians/input 2
echo calling sequence 4 ...
./build/background_subtraction /home/guoqing/Datasets/CDW-2014/dataset/baseline/PETS2006/input 2
echo Done.
