//vtk includes  
#include "vtkButtonWidget.h"  
#include "vtkRenderer.h"  
#include "vtkRenderWindow.h"  
#include "vtkRenderWindowInteractor.h"  
#include "vtkPolyData.h"  
#include "vtkPolyDataMapper.h"  
#include "vtkSphereSource.h"  
#include "vtkSmartPointer.h"  
#include "vtkBoxWidget.h"  
#include "vtkCommand.h"  
#include "vtkActor.h"  
#include "vtkCamera.h"  
#include "vtkConeSource.h"  
#include "vtkInteractorStyleTrackballCamera.h"  
#include "vtkTransform.h"  
#include "vtkProperty2D.h"  
#include "vtkVersion.h"  
#include "vtkOrientationMarkerWidget.h"  
#include "vtkAxesActor.h"  
#include "vtkPropAssembly.h"  
#include "vtkVolume.h"  
#include "vtkLookupTable.h"  
#include "vtkDICOMImageReader.h"  
#include "vtkBMPReader.h"  
#include "vtkPiecewiseFunction.h"  
#include "vtkColorTransferFunction.h"  
#include "vtkVolumeProperty.h"  
#include "vtkVolumeRayCastCompositeFunction.h"  
#include "vtkVolumeRayCastMapper.h"  
#include "vtkImageCast.h"  
#include "vtkOpenGLVolumeTextureMapper3D.h"  
#include "vtkImageThreshold.h"  
#include "vtkImageShiftScale.h"  
#include "vtkImageData.h"  
#include "vtkStructuredPointsWriter.h"  
#include "vtkStructuredPointsReader.h"  
#include "vtkImageShrink3D.h"  
#include "vtkImageGaussianSmooth.h"  
#include "vtkPlanes.h"  
#include "vtkPlane.h"  
#include "vtkFixedPointVolumeRayCastMapper.h"  
#include "vtkImageMask.h"  
#include "vtk3DWidget.h"  
#include "vtkProperty.h"    
#include "vtkContourFilter.h"    
#include "vtkPolyDataNormals.h"    
#include "vtkOutlineFilter.h"    
#include "vtkStripper.h"    
#include "vtkSmoothPolyDataFilter.h"    
#include "vtkImagePlaneWidget.h"  
#include "vtkImageFlip.h"    
#include "vtkImageViewer.h"    
#include "vtkLineSource.h"    
#include "vtkDataSetMapper.h"    
#include "vtkPolyDataWriter.h"    
#include "vtkPolyDataReader.h"  
#include "vtkImageMapToColors.h"  
#include "vtkImageActor.h"  
#include "vtkVolume16Reader.h"  
#include "vtkImplicitPlaneWidget.h"  
#include "vtkLODActor.h"  
#include "vtkTexturedButtonRepresentation.h"  
#include "vtkGlyph3D.h"  
#include "vtkAppendPolyData.h"  
#include "vtkClipPolyData.h"  
#include "vtkSphere.h"  
#include "vtkSampleFunction.h"   
#include "vtkCubeAxesActor2D.h"  
#include "vtkCutter.h"  
#include "vtkLODProp3D.h"  
// #include "vtkWin32RenderWindowInteractor.h"  
#include "vtkCubeSource.h"  
#include "vtkSliderWidget.h"  
#include "vtkSliderRepresentation3D.h"  
#include "vtkInteractorStyleUser.h"  
#include "vtkXMLImageDataWriter.h"  
#include "vtkTransformPolyDataFilter.h"  
#include "vtkXMLPolyDataReader.h"  
#include "vtkWindowToImageFilter.h"  
#include <vtkPointPicker.h>  
#include <vtkObjectFactory.h>  
#include <vtkRendererCollection.h>  
#include "vtkAffineWidget.h"  
#include "vtkAffineRepresentation2D.h"  
#include "vtkPlaneSource.h"  
#include <vtkAffineWidget.h>  
#include <vtkAppendPolyData.h>  
#include <vtkInteractorStyleSwitch.h>  
#include <vtkTextWidget.h>  
#include <vtkTextActor.h>  
#include <vtkTextProperty.h>  
#include <vtkTextRepresentation.h>  
#include <vtkContourWidget.h>  
#include <vtkOrientedGlyphContourRepresentation.h>  
#include <vtkDebugLeaks.h>  
#include <vtkCellArray.h>  
#include <vtkPoints.h>  
#include <vtkMath.h>  
#include <vtkWidgetEvent.h>  
#include <vtkWidgetEventTranslator.h>  
#include <vtkXMLPolyDataReader.h>  
#include <vtkImplicitPlaneRepresentation.h>  
#include "vtkBYUReader.h"  
#include "vtkPLYReader.h"  
#include "vtkSurfaceReconstructionFilter.h"  
#include <vtkImageCanvasSource2D.h>  
#include <vtkInteractorStyleImage.h>  
#include <vtkPointHandleRepresentation2D.h>  
#include <vtkSeedWidget.h>  
#include <vtkSeedRepresentation.h>  
#include "vtkWindowLevelLookupTable.h"  
#include "vtkCaptionActor2D.h"  
#include "vtkCylinderSource.h"  
#include "vtkPropCollection.h"  
#include "vtkTextProperty.h"  
#include "vtkCylinderSource.h"   
#include "vtkAnnotatedCubeActor.h"   
#include "vtkAssembly.h"   
#include <vtkCubeAxesActor.h>  
#include <vtkTextProperty.h>  
#include <vtkActorCollection.h>  
#include <vtkSuperquadricSource.h>  
#include <vtkNew.h>  
#include <vtkPlatonicSolidSource.h>  
#include <vtkLODActor.h>  
#include <vtkLight.h>  
#include <vtkTextProperty.h>  
#include <vtkObjectFactory.h>  
#include <vtkActor2D.h>  
#include <vtkTextProperty.h>  
#include <vtkTextMapper.h>  
#include <vtkTextProperty.h>  
#include <vtkSliderWidget.h>  
#include <vtkWidgetEvent.h>  
#include <vtkCallbackCommand.h>  
#include <vtkWidgetEventTranslator.h>  
#include <vtkSliderWidget.h>  
#include "vtkBMPWriter.h"  
#include "vtkJPEGReader.h"  
#include "vtkSliderRepresentation2D.h"  
#include "vtkTextActor.h"  
#include "vtkTexturedButtonRepresentation2D.h"  
#include "vtkDistanceRepresentation3D.h"  
#include "vtkDistanceWidget.h"  
#include "vtkAngleRepresentation3D.h"  
#include "vtkAngleWidget.h"  
#include "vtkImageViewer2.h"  
#include "vtkTextActor.h"  
#include "vtkCornerAnnotation.h"  
#include "vtkTextureMapToCylinder.h"  
#include "vtkTransformTextureCoords.h"  
#include "vtkImageViewer2.h"  
#include "vtkDICOMImageReader.h"  
#include "vtkOpenGLPolyDataMapper.h"  
#include "vtkClipVolume.h"  
#include "vtkImageToPolyDataFilter.h"  
#include "vtkContourFilter.h"  
#include "vtkImageDataGeometryFilter.h"  
#include "vtkWarpScalar.h"  
#include "vtkPolyDataToImageStencil.h"  
#include "vtkImageStencil.h"  
#include "vtkMetaImageWriter.h"  
#include "vtkImageToImageStencil.h"  
#include "vtkPolyDataToImageStencil.h"  
#include <vtkVersion.h>  
#include <vtkSmartPointer.h>  
#include <vtkPolyData.h>  
#include <vtkImageData.h>  
#include <vtkSphereSource.h>  
#include <vtkMetaImageWriter.h>  
#include <vtkPolyDataToImageStencil.h>  
#include <vtkImageStencil.h>  
#include <vtkPointData.h>  
#include <vtkCutter.h>  
#include <vtkPlane.h>  
#include <vtkStripper.h>  
#include <vtkLinearExtrusionFilter.h>  
#include <vtkXMLPolyDataWriter.h>  
#include <vtkImageData.h>  
#include <vtkMetaImageReader.h>  
#include <vtkSmartPointer.h>  
#include <vtkInteractorStyleImage.h>  
#include <vtkRenderer.h>  
#include <vtkImageActor.h>  
#include <vtkImageMapper3D.h>  
#include <vtkRenderWindow.h>  
#include <vtkRenderWindowInteractor.h>  
#include <vtkTesting.h>  
#include "vtkAlgorithmOutput.h"  
#include "vtkMassProperties.h"  
#include <vtkPolyDataMapper.h>  
#include <vtkActor.h>  
#include <vtkSmartPointer.h>  
#include <vtkRenderWindow.h>  
#include <vtkRenderer.h>  
#include <vtkRenderWindowInteractor.h>  
#include <vtkPolyData.h>  
#include <vtkSphereSource.h>  
#include <vtkWindowToImageFilter.h>  
#include <vtkPNGWriter.h>  
#include "vtkRenderLargeImage.h"  
#include "vtkPropCollection.h"  
#include "vtkVolumeRayCastMapper.h"  
#include "vtkFrustumCoverageCuller.h"  
#include <vtkCullerCollection.h>  
#include "vtkType.h"  
#include "vtkImageDataGeometryFilter.h"  
#include "vtkImageClip.h"  
#include "vtkExtractVOI.h"  
#include "vtkInformation.h"  
#include "vtkTriangleFilter.h"  